/** @type {import('tailwindcss').Config} */
// Theme tokens extracted verbatim from the source design's inline
// `tailwind.config` (Golden Hour Alpine Mist palette) — see the shared
// <head> boilerplate at lines 1-3 of the source markdown.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      // Named 1440px breakpoint (docs call it "desktop") used by ScrollSection
      // for the >=1440px min-height/centering treatment. A plain arbitrary
      // `min-[1440px]:` variant works too without this, but a named breakpoint
      // reads better once 8 more feature pages reuse it — use `desktop:` prefix.
      screens: {
        desktop: '1440px',
      },
      colors: {
        'surface-dim': '#d4dcd7',
        'on-secondary-container': '#3e6d47',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#321300',
        'on-secondary-fixed': '#00210a',
        'tertiary-container': '#893f00',
        'on-tertiary-fixed-variant': '#743400',
        'surface-variant': '#dde4df',
        'tertiary-fixed-dim': '#ffb68b',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#424751',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdbc8',
        'primary-fixed-dim': '#abc7ff',
        'secondary-fixed': '#bcefc0',
        'error-container': '#ffdad6',
        surface: '#f4fbf6',
        'inverse-primary': '#abc7ff',
        'on-secondary-fixed-variant': '#22502d',
        secondary: '#3a6843',
        'surface-tint': '#245dae',
        'on-secondary': '#ffffff',
        'secondary-container': '#b9ecbd',
        'inverse-surface': '#2b322f',
        background: '#f4fbf6',
        'surface-bright': '#f4fbf6',
        'outline-variant': '#c2c6d3',
        tertiary: '#662d00',
        'on-surface': '#161d1a',
        'primary-fixed': '#d7e2ff',
        'inverse-on-surface': '#ebf2ed',
        'on-primary-container': '#aec9ff',
        'surface-container-high': '#e3eae5',
        'on-primary-fixed': '#001b3f',
        outline: '#737783',
        'surface-container-highest': '#dde4df',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        primary: '#003b7d',
        'surface-container-low': '#eef5f0',
        'on-tertiary-container': '#ffb990',
        error: '#ba1a1a',
        'surface-container': '#e8f0eb',
        'on-background': '#161d1a',
        'on-primary-fixed-variant': '#004590',
        'secondary-fixed-dim': '#a0d3a5',
        'primary-container': '#1252a3',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-3xl': '4rem',
        'gutter-desktop': '2rem',
        'space-xxs': '0.25rem',
        'container-max': '1480px',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'space-2xl': '3rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
      },
      fontFamily: {
        'body-sm': ['Manrope'],
        'headline-lg': ['Space Grotesk'],
        'body-md': ['Manrope'],
        'headline-xl': ['Space Grotesk'],
        'display-lg': ['Space Grotesk'],
        'headline-xl-mobile': ['Space Grotesk'],
        'label-caps': ['Manrope'],
        'label-mono': ['JetBrains Mono'],
        'headline-sm': ['Space Grotesk'],
        'display-lg-mobile': ['Space Grotesk'],
        'telemetry-data': ['JetBrains Mono'],
        'body-lg': ['Manrope'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-mono': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'telemetry-data': ['15px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
